# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Publish Nuget Package
        uses: myci-actions/publish-nuget@5
        with:
          filename: SirRandoo.ToolkitPolls
          api-key: ${{ secrets.GITHUB_TOKEN }}
          repo-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
